"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-16 08:56:50.269766

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_debates",
        sa.Column(
            "debate_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("module", sa.Text(), nullable=False),
        sa.Column("evidence_packet", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_a", sa.Text(), nullable=False),
        sa.Column("provider_b", sa.Text(), nullable=False),
        sa.Column("model_a", sa.Text(), nullable=False),
        sa.Column("model_b", sa.Text(), nullable=False),
        sa.Column("round1_a", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("round1_b", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("round2_a", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("round2_b", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("judge_provider", sa.Text(), nullable=False),
        sa.Column("judge_model", sa.Text(), nullable=False),
        sa.Column("verdict", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("consensus_score", sa.REAL(), nullable=False),
        sa.Column("disagreement_axis", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("debate_id", name=op.f("ai_debates_pkey")),
    )
    op.create_index("ai_debates_consensus_idx", "ai_debates", ["consensus_score"], unique=False)
    op.create_table(
        "crosswalk_unmatched",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("raw_name", sa.Text(), nullable=True),
        sa.Column("raw_position", sa.Text(), nullable=True),
        sa.Column("raw_team", sa.Text(), nullable=True),
        sa.Column(
            "first_seen",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("resolved", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("crosswalk_unmatched_pkey")),
        sa.UniqueConstraint(
            "source", "external_id", name=op.f("crosswalk_unmatched_source_external_id_key")
        ),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("run_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("asset", sa.Text(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=True),
        sa.Column("week", sa.SmallInteger(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=True),
        sa.Column("source_etag", sa.Text(), nullable=True),
        sa.Column("source_mtime", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_path", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("run_id", name=op.f("ingest_runs_pkey")),
    )
    op.create_index(
        "ingest_runs_source_idx", "ingest_runs", ["source", "asset", "started_at"], unique=False
    )
    op.create_table(
        "leagues",
        sa.Column(
            "league_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("platform", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("num_teams", sa.SmallInteger(), nullable=False),
        sa.Column("scoring_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("roster_settings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("league_type", sa.Text(), nullable=False),
        sa.Column("is_superflex", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("playoff_teams", sa.SmallInteger(), nullable=True),
        sa.Column("playoff_start_wk", sa.SmallInteger(), nullable=True),
        sa.Column("faab_budget", sa.Integer(), nullable=True),
        sa.Column("my_team_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # leagues_my_team_fkey (use_alter=True) is added below, after league_teams exists.
        sa.PrimaryKeyConstraint("league_id", name=op.f("leagues_pkey")),
        sa.UniqueConstraint(
            "platform",
            "external_id",
            "season",
            name=op.f("leagues_platform_external_id_season_key"),
        ),
    )
    op.create_table(
        "nfl_teams",
        sa.Column("team_abbr", sa.Text(), nullable=False),
        sa.Column("espn_id", sa.Integer(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("conference", sa.Text(), nullable=False),
        sa.Column("division", sa.Text(), nullable=False),
        sa.Column("bye_week", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("team_abbr", name=op.f("nfl_teams_pkey")),
        sa.UniqueConstraint("espn_id", name=op.f("nfl_teams_espn_id_key")),
    )
    op.create_table(
        "players",
        sa.Column(
            "player_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("gsis_id", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=True),
        sa.Column("last_name", sa.Text(), nullable=True),
        sa.Column("normalized_name", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("rookie_year", sa.SmallInteger(), nullable=True),
        sa.Column("height_in", sa.SmallInteger(), nullable=True),
        sa.Column("weight_lb", sa.SmallInteger(), nullable=True),
        sa.Column("college", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("player_id", name=op.f("players_pkey")),
        sa.UniqueConstraint("gsis_id", name=op.f("players_gsis_id_key")),
    )
    op.create_index(
        "players_normalized_name_pos_idx", "players", ["normalized_name", "position"], unique=False
    )
    op.create_table(
        "stadiums",
        sa.Column("stadium_id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=False),
        sa.Column("longitude", sa.Double(), nullable=False),
        sa.Column("altitude_ft", sa.Integer(), nullable=True),
        sa.Column("heading_deg", sa.REAL(), nullable=True),
        sa.Column("surface_type", sa.Text(), nullable=True),
        sa.Column("roof_type", sa.Text(), nullable=True),
        sa.Column("tz", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("stadium_id", name=op.f("stadiums_pkey")),
    )
    op.create_table(
        "adp",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("num_teams", sa.SmallInteger(), nullable=False),
        sa.Column("scrape_date", sa.Date(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("adp", sa.REAL(), nullable=False),
        sa.Column("adp_stdev", sa.REAL(), nullable=True),
        sa.Column("times_drafted", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name=op.f("adp_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "source", "format", "num_teams", "scrape_date", "player_id", name=op.f("adp_pkey")
        ),
    )
    op.create_table(
        "drafts",
        sa.Column(
            "draft_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("draft_type", sa.Text(), nullable=False),
        sa.Column("rounds", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("my_slot", sa.SmallInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.league_id"],
            name=op.f("drafts_league_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("draft_id", name=op.f("drafts_pkey")),
        sa.UniqueConstraint(
            "league_id", "external_id", name=op.f("drafts_league_id_external_id_key")
        ),
    )
    op.create_table(
        "games",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("season_type", sa.Text(), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team", sa.Text(), nullable=False),
        sa.Column("away_team", sa.Text(), nullable=False),
        sa.Column("stadium_id", sa.Text(), nullable=True),
        sa.Column("spread_line", sa.REAL(), nullable=True),
        sa.Column("total_line", sa.REAL(), nullable=True),
        sa.Column("home_moneyline", sa.Integer(), nullable=True),
        sa.Column("away_moneyline", sa.Integer(), nullable=True),
        sa.Column("roof", sa.Text(), nullable=True),
        sa.Column("surface", sa.Text(), nullable=True),
        sa.Column("div_game", sa.Boolean(), nullable=True),
        sa.Column("home_rest", sa.SmallInteger(), nullable=True),
        sa.Column("away_rest", sa.SmallInteger(), nullable=True),
        sa.Column("neutral_site", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("home_score", sa.SmallInteger(), nullable=True),
        sa.Column("away_score", sa.SmallInteger(), nullable=True),
        sa.Column("temp_f", sa.REAL(), nullable=True),
        sa.Column("wind_mph", sa.REAL(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team"], ["nfl_teams.team_abbr"], name=op.f("games_away_team_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["home_team"], ["nfl_teams.team_abbr"], name=op.f("games_home_team_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["stadium_id"], ["stadiums.stadium_id"], name=op.f("games_stadium_id_fkey")
        ),
        sa.PrimaryKeyConstraint("game_id", name=op.f("games_pkey")),
    )
    op.create_index(
        "games_kickoff_brin", "games", ["kickoff_at"], unique=False, postgresql_using="brin"
    )
    op.create_index("games_season_week_idx", "games", ["season", "week"], unique=False)
    op.create_table(
        "league_teams",
        sa.Column(
            "league_team_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("manager_name", sa.Text(), nullable=True),
        sa.Column("draft_slot", sa.SmallInteger(), nullable=True),
        sa.Column("faab_remaining", sa.Integer(), nullable=True),
        sa.Column("waiver_priority", sa.SmallInteger(), nullable=True),
        sa.Column("is_me", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.league_id"],
            name=op.f("league_teams_league_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("league_team_id", name=op.f("league_teams_pkey")),
        sa.UniqueConstraint(
            "league_id", "external_id", name=op.f("league_teams_league_id_external_id_key")
        ),
        sa.UniqueConstraint(
            "league_id", "league_team_id", name="league_teams_league_id_league_team_id_key"
        ),
    )
    op.create_table(
        "player_external_ids",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("confidence", sa.REAL(), server_default=sa.text("1.0"), nullable=False),
        sa.Column("match_method", sa.Text(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.player_id"],
            name=op.f("player_external_ids_player_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("source", "external_id", name=op.f("player_external_ids_pkey")),
    )
    op.create_index(
        "player_external_ids_player_idx", "player_external_ids", ["player_id"], unique=False
    )
    op.create_table(
        "player_injury_status",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("report_status", sa.Text(), nullable=True),
        sa.Column("practice_status", sa.Text(), nullable=True),
        sa.Column("injury_body_part", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name=op.f("player_injury_status_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "player_id",
            "season",
            "week",
            "observed_at",
            "source",
            name=op.f("player_injury_status_pkey"),
        ),
    )
    op.create_table(
        "projection_correlations",
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("player_a", sa.UUID(), nullable=False),
        sa.Column("player_b", sa.UUID(), nullable=False),
        sa.Column("rho", sa.REAL(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "player_a < player_b", name=op.f("projection_correlations_canonical_pair_order_check")
        ),
        sa.ForeignKeyConstraint(
            ["player_a"], ["players.player_id"], name=op.f("projection_correlations_player_a_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["player_b"], ["players.player_id"], name=op.f("projection_correlations_player_b_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "season", "week", "player_a", "player_b", name=op.f("projection_correlations_pkey")
        ),
    )
    op.create_table(
        "projections",
        sa.Column(
            "projection_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=False),
        sa.Column("mean_points", sa.REAL(), nullable=False),
        sa.Column("gamma_shape", sa.REAL(), nullable=False),
        sa.Column("gamma_scale", sa.REAL(), nullable=False),
        sa.Column("floor_p10", sa.REAL(), nullable=True),
        sa.Column("ceiling_p90", sa.REAL(), nullable=True),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["league_id"], ["leagues.league_id"], name=op.f("projections_league_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name=op.f("projections_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint("projection_id", name=op.f("projections_pkey")),
        sa.UniqueConstraint(
            "player_id",
            "season",
            "week",
            "league_id",
            "source",
            "model_version",
            name="projections_scope_key",
        ),
    )
    op.create_index(
        "projections_lookup_idx",
        "projections",
        ["season", "week", "source", "model_version"],
        unique=False,
    )
    op.create_table(
        "recommendations",
        sa.Column(
            "recommendation_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("module", sa.Text(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("final_output", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("engine_version", sa.Text(), nullable=False),
        sa.Column("debate_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("action_taken", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_id"], ["leagues.league_id"], name=op.f("recommendations_league_id_fkey")
        ),
        sa.PrimaryKeyConstraint("recommendation_id", name=op.f("recommendations_pkey")),
    )
    op.create_index(
        "recommendations_module_idx", "recommendations", ["module", "season", "week"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column(
            "transaction_id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("faab_spent", sa.Integer(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.league_id"],
            name=op.f("transactions_league_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("transaction_id", name=op.f("transactions_pkey")),
        sa.UniqueConstraint(
            "league_id",
            "external_id",
            name=op.f("transactions_league_id_external_id_key"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_table(
        "draft_picks",
        sa.Column("draft_id", sa.UUID(), nullable=False),
        sa.Column("pick_no", sa.SmallInteger(), nullable=False),
        sa.Column("round", sa.SmallInteger(), nullable=False),
        sa.Column("draft_slot", sa.SmallInteger(), nullable=False),
        sa.Column("league_team_id", sa.UUID(), nullable=True),
        sa.Column("player_id", sa.UUID(), nullable=True),
        sa.Column("is_keeper", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("auction_amount", sa.Integer(), nullable=True),
        sa.Column("picked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["drafts.draft_id"],
            name=op.f("draft_picks_draft_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["league_team_id"],
            ["league_teams.league_team_id"],
            name=op.f("draft_picks_league_team_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name=op.f("draft_picks_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint("draft_id", "pick_no", name=op.f("draft_picks_pkey")),
    )
    op.create_index("draft_picks_player_idx", "draft_picks", ["player_id"], unique=False)
    op.create_table(
        "game_weather_forecasts",
        sa.Column("game_id", sa.Text(), nullable=False),
        sa.Column("forecast_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temp_f", sa.REAL(), nullable=True),
        sa.Column("wind_mph", sa.REAL(), nullable=True),
        sa.Column("wind_gust_mph", sa.REAL(), nullable=True),
        sa.Column("wind_dir_deg", sa.REAL(), nullable=True),
        sa.Column("precip_mm", sa.REAL(), nullable=True),
        sa.Column("precip_prob", sa.REAL(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.game_id"], name=op.f("game_weather_forecasts_game_id_fkey")
        ),
        sa.PrimaryKeyConstraint("game_id", "forecast_at", name=op.f("game_weather_forecasts_pkey")),
    )
    op.create_table(
        "matchups",
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("matchup_no", sa.SmallInteger(), nullable=False),
        sa.Column("home_team_id", sa.UUID(), nullable=False),
        sa.Column("away_team_id", sa.UUID(), nullable=True),
        sa.Column("home_points", sa.REAL(), nullable=True),
        sa.Column("away_points", sa.REAL(), nullable=True),
        sa.ForeignKeyConstraint(
            ["league_id", "away_team_id"],
            ["league_teams.league_id", "league_teams.league_team_id"],
            name="matchups_away_team_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["league_id", "home_team_id"],
            ["league_teams.league_id", "league_teams.league_team_id"],
            name="matchups_home_team_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["league_id"],
            ["leagues.league_id"],
            name=op.f("matchups_league_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("league_id", "week", "matchup_no", name=op.f("matchups_pkey")),
    )
    op.create_table(
        "player_week_actuals",
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("season", sa.SmallInteger(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("league_id", sa.UUID(), nullable=False),
        sa.Column("game_id", sa.Text(), nullable=True),
        sa.Column("fantasy_points", sa.REAL(), nullable=False),
        sa.Column("snap_pct", sa.REAL(), nullable=True),
        sa.Column("target_share", sa.REAL(), nullable=True),
        sa.Column("carry_share", sa.REAL(), nullable=True),
        sa.Column("rz_touches", sa.SmallInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["game_id"], ["games.game_id"], name=op.f("player_week_actuals_game_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["league_id"], ["leagues.league_id"], name=op.f("player_week_actuals_league_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name=op.f("player_week_actuals_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "player_id", "season", "week", "league_id", name=op.f("player_week_actuals_pkey")
        ),
    )
    op.create_table(
        "roster_slots",
        sa.Column("league_team_id", sa.UUID(), nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("player_id", sa.UUID(), nullable=False),
        sa.Column("slot", sa.Text(), nullable=False),
        sa.Column("is_starter", sa.Boolean(), nullable=False),
        sa.Column(
            "captured_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["league_team_id"],
            ["league_teams.league_team_id"],
            name=op.f("roster_slots_league_team_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], name=op.f("roster_slots_player_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "league_team_id", "week", "player_id", name=op.f("roster_slots_pkey")
        ),
    )
    # ### end Alembic commands ###
    # Hand-added: cyclic leagues <-> league_teams FK (use_alter=True in the model).
    # Autogenerate rendered it inline in create_table("leagues"), where CREATE TABLE
    # silently skips use_alter constraints, so it must be emitted as a separate ALTER.
    op.create_foreign_key(
        "leagues_my_team_fkey",
        "leagues",
        "league_teams",
        ["league_id", "my_team_id"],
        ["league_id", "league_team_id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Hand-added: drop the cyclic FK first so league_teams can be dropped below.
    op.drop_constraint("leagues_my_team_fkey", "leagues", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("roster_slots")
    op.drop_table("player_week_actuals")
    op.drop_table("matchups")
    op.drop_table("game_weather_forecasts")
    op.drop_index("draft_picks_player_idx", table_name="draft_picks")
    op.drop_table("draft_picks")
    op.drop_table("transactions")
    op.drop_index("recommendations_module_idx", table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index("projections_lookup_idx", table_name="projections")
    op.drop_table("projections")
    op.drop_table("projection_correlations")
    op.drop_table("player_injury_status")
    op.drop_index("player_external_ids_player_idx", table_name="player_external_ids")
    op.drop_table("player_external_ids")
    op.drop_table("league_teams")
    op.drop_index("games_season_week_idx", table_name="games")
    op.drop_index("games_kickoff_brin", table_name="games", postgresql_using="brin")
    op.drop_table("games")
    op.drop_table("drafts")
    op.drop_table("adp")
    op.drop_table("stadiums")
    op.drop_index("players_normalized_name_pos_idx", table_name="players")
    op.drop_table("players")
    op.drop_table("nfl_teams")
    op.drop_table("leagues")
    op.drop_index("ingest_runs_source_idx", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("crosswalk_unmatched")
    op.drop_index("ai_debates_consensus_idx", table_name="ai_debates")
    op.drop_table("ai_debates")
    # ### end Alembic commands ###
